name: parsec_web
description: Web implementation of the parsec plugin using WebAssembly via dart:js_interop.
version: 0.1.2
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec_web

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  parsec_platform_interface: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: parsec
    platforms:
      web:
        pluginClass: ParsecWebPlugin
        fileName: parsec_web.dart

executables:
  generate: generate
